name: Build and Release Dashboard

on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    name: Build macOS Application
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/dashboard/requirements.txt
          pip install pyinstaller==6.14.1

      - name: Build application with PyInstaller
        working-directory: apps/dashboard
        run: |
          pyinstaller main.spec --clean --noconfirm

      - name: Create DMG
        run: |
          cd apps/dashboard/dist
          hdiutil create -volname "Behavior Box Dashboard" -srcfolder "Behavior Box Dashboard.app" -ov -format UDZO "Behavior Box Dashboard.dmg"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: apps/dashboard/dist/Behavior Box Dashboard.dmg
          retention-days: 1

  build-windows:
    name: Build Windows Application
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/dashboard/requirements.txt
          pip install pyinstaller==6.14.1

      - name: Convert PNG icon to ICO for Windows
        working-directory: apps/dashboard
        shell: cmd
        run: |
          python -c "from PIL import Image; img = Image.open('assets/icon.png'); img.save('assets/icon.ico', format='ICO')"

      - name: Build application with PyInstaller
        working-directory: apps/dashboard
        shell: cmd
        run: |
          pyinstaller main.spec --clean --noconfirm

      - name: Upload Windows executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: apps/dashboard/dist/Behavior Box Dashboard/Behavior Box Dashboard.exe
          retention-days: 1

  create-release:
    name: Create Release
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Download macOS DMG
        uses: actions/download-artifact@v4
        with:
          name: macos-dmg

      - name: Download Windows executable
        uses: actions/download-artifact@v4
        with:
          name: windows-exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            Behavior Box Dashboard.dmg
            Behavior Box Dashboard.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false

